package com.example.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material.icons.outlined.Share
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.data.model.BusinessProfile
import com.example.data.model.Recommendation
import com.example.data.model.SwotAnalysis
import com.example.ui.theme.BluePrimary
import com.example.ui.theme.SuccessGreen

@Composable
fun ReportsScreen(
    profile: BusinessProfile,
    swot: SwotAnalysis,
    recommendations: List<Recommendation>,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var showCopySnackbar by remember { mutableStateOf(false) }

    fun generateFullReportText(): String {
        return """
            =======================================================
            EXECUTIVE STRATEGIC REPORT: ${profile.name.uppercase()}
            Industry: ${profile.industry} (${profile.businessType})
            =======================================================
            
            1. EXECUTIVE FINANCIAL OVERVIEW:
            - Monthly Run-Rate Revenue: $${String.format("%,.0f", profile.monthlyRevenue)}
            - Operating Expenses: $${String.format("%,.0f", profile.monthlyExpenses)}
            - Net Operating Profit: $${String.format("%,.0f", profile.netProfit)} (${String.format("%.1f", profile.profitMarginPercentage)}% Margin)
            - Active Client Community: ${String.format("%,d", profile.customerCount)}
            - Monthly Marketing Investment: $${String.format("%,.0f", profile.marketingBudget)}
            - Strategic Goal: ${profile.businessGoal}
            
            2. STRATEGIC SWOT DIAGNOSTIC:
            STRENGTHS:
            ${swot.strengths.joinToString("\n") { "• ${it.title}: ${it.description}" }}
            
            WEAKNESSES:
            ${swot.weaknesses.joinToString("\n") { "• ${it.title}: ${it.description}" }}
            
            OPPORTUNITIES:
            ${swot.opportunities.joinToString("\n") { "• ${it.title}: ${it.description}" }}
            
            THREATS:
            ${swot.threats.joinToString("\n") { "• ${it.title}: ${it.description}" }}
            
            3. PRIORITY ACTION CHECKLIST:
            ${recommendations.take(5).joinToString("\n") { "• [${if (it.isCompleted) "COMPLETED" else "PENDING"}] ${it.title} (ROI: ${it.estimatedRoi})" }}
            
            Report generated by AI-Powered Business Consultant.
        """.trimIndent()
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp)
            .testTag("reports_screen"),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
            verticalAlignment = Alignment.CenterVertically
        ) {
            Column {
                Text(
                    text = "Executive Strategic Dossier",
                    style = MaterialTheme.typography.headlineSmall,
                    fontWeight = FontWeight.Bold
                )
                Text(
                    text = "Comprehensive performance brief ready for board review.",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )
            }

            IconButton(onClick = {
                val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                clipboard.setPrimaryClip(ClipData.newPlainText("Executive Report", generateFullReportText()))
                showCopySnackbar = true
            }) {
                Icon(Icons.Outlined.Share, contentDescription = "Export Report", tint = BluePrimary)
            }
        }

        if (showCopySnackbar) {
            Card(
                colors = CardDefaults.cardColors(containerColor = SuccessGreen.copy(alpha = 0.15f)),
                shape = RoundedCornerShape(8.dp)
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(10.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Icon(Icons.Default.CheckCircle, contentDescription = null, tint = SuccessGreen)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Executive report copied to system clipboard!", color = SuccessGreen, fontWeight = FontWeight.Medium)
                }
            }
        }

        // Report Document Preview Card
        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(16.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
            elevation = CardDefaults.cardElevation(defaultElevation = 3.dp)
        ) {
            Column(
                modifier = Modifier
                    .padding(20.dp)
                    .fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(14.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = profile.name,
                        style = MaterialTheme.typography.titleLarge,
                        fontWeight = FontWeight.Bold
                    )
                    Surface(
                        shape = RoundedCornerShape(6.dp),
                        color = MaterialTheme.colorScheme.primaryContainer
                    ) {
                        Text(
                            text = "Confidential",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.onPrimaryContainer,
                            modifier = Modifier.padding(horizontal = 8.dp, vertical = 4.dp)
                        )
                    }
                }

                Text(
                    text = "Prepared by: AI Business Strategy Engine • Evaluated for: Executive Founder",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant
                )

                HorizontalDivider()

                Text(
                    text = "1. Financial & Operational Summary",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Column {
                        Text("Monthly Revenue", style = MaterialTheme.typography.labelSmall)
                        Text("$${String.format("%,.0f", profile.monthlyRevenue)}", fontWeight = FontWeight.Bold)
                    }
                    Column {
                        Text("Monthly OpEx", style = MaterialTheme.typography.labelSmall)
                        Text("$${String.format("%,.0f", profile.monthlyExpenses)}", fontWeight = FontWeight.Bold)
                    }
                    Column {
                        Text("Net Profit Margin", style = MaterialTheme.typography.labelSmall)
                        Text("${String.format("%.1f", profile.profitMarginPercentage)}%", fontWeight = FontWeight.Bold, color = SuccessGreen)
                    }
                }

                HorizontalDivider()

                Text(
                    text = "2. SWOT Executive Highlights",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )

                Text(
                    text = "• Top Strength: ${swot.strengths.firstOrNull()?.title ?: "Stable Unit Economics"}\n" +
                            "• Key Vulnerability: ${swot.weaknesses.firstOrNull()?.title ?: "Marketing Overhead Concentration"}\n" +
                            "• Prime Opportunity: ${swot.opportunities.firstOrNull()?.title ?: "B2B Expansion"}\n" +
                            "• External Risk: ${swot.threats.firstOrNull()?.title ?: "Rising Ad Inflation"}",
                    style = MaterialTheme.typography.bodyMedium,
                    lineHeight = 22.sp
                )

                HorizontalDivider()

                Text(
                    text = "3. Strategic Action Priorities",
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold
                )

                recommendations.take(4).forEach { rec ->
                    Row(
                        modifier = Modifier.padding(vertical = 3.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            imageVector = if (rec.isCompleted) Icons.Default.CheckCircle else Icons.Default.RadioButtonUnchecked,
                            contentDescription = null,
                            tint = if (rec.isCompleted) SuccessGreen else MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.size(16.dp)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            text = "${rec.title} (${rec.estimatedRoi})",
                            style = MaterialTheme.typography.bodyMedium
                        )
                    }
                }

                Spacer(modifier = Modifier.height(10.dp))

                Button(
                    onClick = {
                        val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                        clipboard.setPrimaryClip(ClipData.newPlainText("Executive Report", generateFullReportText()))
                        showCopySnackbar = true
                    },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(10.dp)
                ) {
                    Icon(Icons.Default.ContentCopy, contentDescription = null)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text("Copy Complete Executive Dossier")
                }
            }
        }

        Spacer(modifier = Modifier.height(24.dp))
    }
}
